spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: admin-server

server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.99:8888/eureka
  instance:
      prefer-ip-address: true
      ip-address: 192.168.0.99

